### ISSUE TITLE
"<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by anthr76** [Fmstrat/lcs#1]
Hello!

I'm trying this out but seems like it's tell me it isn't receiving valid JSON 

```
Searched for community reddit@lemmy.ml: FetchError: invalid json response body at https://lemmy.kutara.io/api/v3/community?name=reddit%40lemmy.ml reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
Added community reddit@lemmy.ml: 327
```

Though if I follow the link it does?

**Comment by Fmstrat** [comment]
Duplicate of https://github.com/Fmstrat/lcs/issues/2

This happens when the instance returns an error, likely too busy.
