### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by dr460nf1r3** [Fmstrat/lcs#11]
Got the following issue: 
~~~
(node:1) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> lemmy-subscriber@1.0.0 start
> node index.js

Error: Not Found
    at LemmyHttp.<anonymous> (/app/node_modules/lemmy-js-client/dist/http.js:1043:19)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/lemmy-js-client/dist/http.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Sleeping 240 minutes
~~~

I'm using the default config with just the `LOCAL_*` variables for login exchanged. I'm not sure whether this is related to lcs or lemmy-js-client, but I thought I'd report it here. The same `LOCAL_*` variables are also in place with lds, and they are working without issues there.

**Comment by Fmstrat** [comment]
Complete in latest version.

**Comment by dr460nf1r3** [comment]
Hi, thanks for the update :) I'm getting the following error now: 
~~~
> lemmy-subscriber@1.0.0 start
> node index.js

Error: incorrect_login
    at LemmyHttp.<anonymous> (/app/node_modules/lemmy-js-client/dist/http.js:938:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/lemmy-js-client/dist/http.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Sleeping 240 minutes
~~~

Looking at the commit, it seems you accidentally committed a change that shouldn't have been committed?

https://github.com/Fmstrat/lcs/commit/2d85b51cdb6d5aaa4710af462169ba69eaaca7bc#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R152

**Comment by Fmstrat** [comment]
Doh, was in a hurry with the holiday! Fixed in latest.

**Comment by dr460nf1r3** [comment]
Thank you very much, can confirm its working now. Merry Christmas, if you celebrate it, and a few good days to you!

**Comment by Fmstrat** [comment]
Glad to hear it, and merry Christmas to you as well.
