### ISSUE TITLE
Add version 0.19 API compatible login

### ISSUE THREAD

**Issue by citking** [Fmstrat/lcs#9]
LCS returns:

FetchError: invalid json response body at https://daring.lemmy.fan/api/v3/user/login reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

    at /app/node_modules/node-fetch/lib/index.js:273:32

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

  type: 'invalid-json'

on Lemmy 0.19. 

Any chance the login logic can be updated to use the new Lemmy login API?

**Comment by SirMaple** [comment]
I'm also getting this error on Lemmy 0.19.1

```
Checking programming.dev for posts of TopAll
FetchError: invalid json response body at https://programming.dev/api/v3/post/list?type_=All&sort=TopAll&limit=100 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}
```

**Comment by codypace68** [comment]
I have created a pull req for this.

I know there is already a separate branch. But I've ran this through and it's working fine on version .19

https://github.com/Fmstrat/lcs/pull/10

**Comment by Fmstrat** [comment]
Complete in latest version.
